### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Vanchen07** [khoa0101/Etchy#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by khoa0101** [comment]
I've finished my auth feature. Can you check it out?

**Comment by Vanchen07** [comment]
-can you add styling to better reflect the final styling? 
-On the modal, there is a button to login and one to sign in. Same issue with register/sign up

**Comment by khoa0101** [comment]
Did you look at the development branch or the main branch?

**Comment by Vanchen07** [comment]
I looked at whichever one was on Heroku.

**Comment by khoa0101** [comment]
I've pushed it on to Heroku. It should be ready for review now.

**Comment by Vanchen07** [comment]
Looks good! Last thing is to handle when users go to random route which should either redirect or show a 404 page

**Comment by khoa0101** [comment]
I've updated my routes. It should no longer render the app if you enter a random url.

**Comment by Vanchen07** [comment]
Cool thanks!
