### ISSUE TITLE
Product

### ISSUE THREAD

**Issue by khoa0101** [khoa0101/Etchy#5]
# Product
## Functionality
 
- [x] Smooth, bug free navigation

### Product Index

- [x] Display a list of products
- [x] Can click on images and the product's info to go to the product show page.

### Product show

- [x] Should be able to refresh the page
- [x] Should display info and images
### Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have cursor: pointer on hover
- [x]  Remove Redux logger and all console.log()'s from production

### Seeds

- [x]  Adequate and appropriate seeds

**Comment by khoa0101** [comment]
Products MVP is ready for check.

**Comment by Vanchen07** [comment]
Looks great! Side question: Why does the number of sales for the same user differ?

**Comment by khoa0101** [comment]
I think the number of sales correspond with how many of that product sold.
